name: Test Streamlit App

on:
  push:
    branches:
      - main

jobs:
  test-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt     
          
      - name: Run flake8
        run: |
          flake8 main.py

      - name: Check for errors
        if: failure()
        run: |
          echo "Error: flake8 check failed"
          
       # юнит тесты
      - name: Run tests
        run: |
          pytest tests/tests.py

